### PR TITLE
Feature/documentation updates

### PR DESCRIPTION
**Pull request by JesseHilario**
Hi, could you please review my changes?

### CODE REVIEW

**Comment by RadhikaNanda** [comment]
broken links on theme_product_development

**Comment by RadhikaNanda** [comment]
on all initiatives, broken links to epics

**Comment by RadhikaNanda** [comment]
broken link on epic_legal_compliance.md for Story 1

**Comment by balajicb-bc75** [comment]
make bullet points for stories' acceptance criteria for readability

**Comment by balajicb-bc75** [comment]
add title for initiative_legal_technical_website_template.md

**Pull request merged**
